### ISSUE TITLE
Cannot install opsi-webgui 

### ISSUE THREAD

**Issue by STJS0** [opsi-org/opsi-webgui#1]
Installing Docker Desktop version on Ubuntu 22

 Whenever I try to install opsi-webgui via apt it cannot locate the package
 E: Unable to locate package opsi-webgui
 
 Contents of  /etc/apt/sources.list.d/opsi.list:                                                                                                                        

deb [signed-by=/usr/local/share/keyrings/opsi-obs.gpg] https://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.3:/stable/xUbuntu_22.04/ /

The file is located here when browsing manually but the server will not locate it via apt. Downloading manually results in a tar file error 
sudo tar -xzf opsi-webgui.tar.gz 

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now

**Comment by AjGaht** [comment]
Faced the same issue. Installation is not straight forward.
Manually edited the sources.list file and still unable to install the package.

**Comment by j-a-n** [comment]
Hello,
It is probably a problem with a mirror or a proxy.
https://download.opensuse.org is provided via mirror servers.
Please try to use another mirror.
You can find the list of mirrors here:
https://mirrors.opensuse.org/
You can use the Build Service Repository link to navigate to the contents of the repository.
Here is an example URL to the current stable opsi-webgui package for the mirror ftp.gwdg.de:
https://ftp.gwdg.de/pub/opensuse/repositories/home:/uibmz:/opsi:/4.3:/stable/xUbuntu_22.04/all/opsi-webgui_4.3.30-1_all.deb

If your problem persists, please use https:/forum.opsi.org for further assistance.
